# Generated by Django 5.1.3 on 2024-11-27 12:34

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Enter car make', max_length=50)),
                ('model', models.CharField(help_text='Enter car model', max_length=50)),
                ('year', models.IntegerField(help_text='Enter car year', max_length=4, null=True)),
                ('engine', models.CharField(help_text='Enter car engine', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter service name (e.g., Change oil)', max_length=200, verbose_name='Service')),
                ('price', models.FloatField(help_text='Enter service price', verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='Car plate', max_length=20, verbose_name='National number')),
                ('VIN_code', models.CharField(help_text='17 characters unique number, more: <a href=https://www.autocheck.com/vehiclehistory/vin-basics>VIN</a>', max_length=17, verbose_name='VIN code')),
                ('client', models.CharField(help_text='Name Surname', max_length=50, verbose_name='Client name')),
                ('car_model_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('deadline', models.DateField(null=True, verbose_name='Deadline')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.car')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Order unique ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order')),
                ('service_id', models.ManyToManyField(help_text='Add services to the order', to='autoservice.service')),
            ],
        ),
    ]
