# Generated by Django 5.1.3 on 2024-11-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.CharField(help_text='Enter car year', max_length=4, null=True),
        ),
    ]
