# Generated by Django 5.1.3 on 2024-11-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car model', 'verbose_name_plural': 'Car models'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Order line', 'verbose_name_plural': 'Order lines'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='order',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car'),
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='service_id',
        ),
        migrations.AddField(
            model_name='orderline',
            name='service_id',
            field=models.ForeignKey(help_text='Add services to the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service'),
        ),
    ]
