# Generated by Django 5.1.3 on 2024-11-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Pending'), ('Accepted', 'Order Accepted'), ('In-progress', 'Service In-progress'), ('Done', 'Service Done'), ('Finalized', ' Order Finalized')], default='Pending', help_text='Order Status', max_length=11),
        ),
    ]
