# Generated by Django 5.1.3 on 2024-12-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Pending'), ('Accepted', 'Order Accepted'), ('In-progress', 'Service In-progress'), ('Done', 'Service Done'), ('Finalized', 'Order Finalized')], default='Pending', help_text='Order Status', max_length=11),
        ),
    ]
