# Generated by Django 5.1.3 on 2024-12-05 13:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_alter_order_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(default='Great customer'),
        ),
    ]
